#!/bin/sh

do_run ()
{
  echo $*
  if $* ; then
    true
  else
    exit $?
  fi
}


if test "$#" -eq 0 ; then
  earname=isacrodi.ear
else
  earname="${1}"
fi

cd ejbjar
do_run jar cvmf META-INF/MANIFEST.MF ../ear/isacrodi-ejb.jar *
cd ../war
do_run jar cvmf META-INF/MANIFEST.MF ../ear/isacrodi-web.war *
cd ../ear
do_run jar cvf ../${earname} *

