package org.isacrodi.ejb.entity;

import java.io.Serializable;


/**
 * Interface to be implemented by all Isacrodi entities.
 *
 * <p>This interface is intended to help ensure consistency of
 * Isacrodi entity implementations and also to support generic
 * programming.</p>
 */
public interface IsacrodiEntity extends Serializable
{
  /**
   * Get the ID of this entity.
   *
   * <p>Informational note: All entities have a corresponding {@code
   * setId} method of course, but this should never be called by
   * client code as IDs are autogenerated. Therefore, the {@link
   * IsacrodiEntity} interface does not declare this mutator.</p>
   */
  Integer getId();

  /**
   * Unlink all associations of this entity.
   *
   * <p>Notice that this may leave the persistent entity base in an
   * inconsistent state if the association is not optional for an
   * associated entity.</p>
   */
  // idea: use boolean return value to indicate success of unlink operation?
  void unlink();
}
